### ISSUE TITLE
Datachange example

### ISSUE THREAD

**Issue by vierlijner** [ArturDias98/OpcDaNetCore#1]
Hi, Can you make an example how to add an event handler on the datachange event from the subscription?
So I want to do something if a value from a item changes. Please in your example project and maybe in the documentation (readme).

Thanks in advance.

**Comment by ArturDias98** [comment]
Ok. I will update the readme file.
For now you can check the example in [Project Sample](https://github.com/ArturDias98/OpcDaNetCore/blob/master/OpcDaNetCore.Sample/Program.cs).  
```csharp
using var server = await new OpcDaFactory()
    .WithIp("localhost")
    .WithServerName("Kepware.KEPServerEX.V5")
    .WithGroup(group1, group2)
    .WithDataChangedCallback(PrintValues)
    .BuildAsync();

static void PrintValues(IEnumerable<ItemDataValue> items)
{
    foreach (var item in items)
    {
        Console.WriteLine($"{item.ItemName}: {item.Value}");
    }
}
```

**Comment by vierlijner** [comment]
Yes I saw this, but I thought that the .WithDataChangedCallBack() a function was when the DataChanged event failed this function was called and you can do someting else.
Thanks for the quick response.
